### ISSUE TITLE
format issue with --cucumber-json option

### ISSUE THREAD

**Issue by vin-d** [radish-bdd/radish#103]
I'm trying to use radish with jenkins but the Post-build actions "Publlish Cucumber test result report" from Jenkins doesn't like the fact the the duration field from the result json is a string.

Jenkins error : 
```
+ radish calculator.feature --cucumber-json=calculator-result.json
Feature: My first feature file using radish  # calculator.feature
    In order to test my awesome software
    I need an awesome BDD tool like radish
    to test my software.

    Scenario: Test my calculator

        Given I have the numbers 5 and 6

        Given I have the numbers 5 and 6

        When I sum them

        When I sum them

        Then I expect the result to be 11

        Then I expect the result to be 11

1 features (1 passed)
1 scenarios (1 passed)
3 steps (3 passed)
Run 1493908920 finished within 0:0.000904 minutes
[Cucumber Tests] Parsing results.
[Cucumber Tests] parsing calculator-result.json
ERROR: Build step failed with exception
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at gherkin.JSONParser.getLong(JSONParser.java:235)
	at gherkin.JSONParser.duration(JSONParser.java:216)
	at gherkin.JSONParser.step(JSONParser.java:115)
	at gherkin.JSONParser.parse(JSONParser.java:51)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parse(CucumberJSONParser.java:78)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parse(CucumberJSONParser.java:44)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:161)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:107)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.FilePath.act(FilePath.java:974)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl.parseResult(DefaultTestResultParserImpl.java:101)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parseResult(CucumberJSONParser.java:101)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.publishReport(CucumberTestResultArchiver.java:128)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:107)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1758)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Publish Cucumber test result report' marked build as failure
```

and I have used the example from the getting started section of http://radish-bdd.io/

my result file from doing `` radish calculator.feature --cucumber-json=result.json`` is 
```json
[
    {
        "description": "In order to test my awesome software\nI need an awesome BDD tool like radish\nto test my software.", 
        "elements": [
            {
                "description": "", 
                "id": "1", 
                "keyword": "Scenario", 
                "line": 6, 
                "name": "Test my calculator", 
                "steps": [
                    {
                        "keyword": "Given", 
                        "line": 7, 
                        "name": "Given I have the numbers 5 and 6", 
                        "result": {
                            "duration": "0.0002360000", 
                            "status": "passed"
                        }
                    }, 
                    {
                        "keyword": "When", 
                        "line": 8, 
                        "name": "When I sum them", 
                        "result": {
                            "duration": "0.0000700000", 
                            "status": "passed"
                        }
                    }, 
                    {
                        "keyword": "Then", 
                        "line": 9, 
                        "name": "Then I expect the result to be 11", 
                        "result": {
                            "duration": "0.0000740000", 
                            "status": "passed"
                        }
                    }
                ], 
                "tags": [], 
                "type": "scenario"
            }
        ], 
        "id": "1", 
        "keyword": "Feature", 
        "line": 1, 
        "name": "My first feature file using radish", 
        "tags": [], 
        "type": "feature", 
        "uri": "calculator.feature"
    }
]
```

So, is the Jenkins plugin buggy or is it the --cucumber-json option from radish which is ?
And, can it be fixed ?
Thank You.

**Comment by timofurrer** [comment]
Thanks for the report!

Unfortunately, I can't find any precise documentation or specification about it.
However, `cucumber-ruby` seems to use *nanoseconds* as *float* for the duration. See https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/formatter/json.rb#L209

I think that it does not make any sense to have that kind of precision in this case. However, to be compatible with cucumber I'm going to implement it with nanoseconds.

If you find any specs about the JSON format, please let me know!

**Comment by vin-d** [comment]
Thank you for the fast response and fix.

For what I've seen from files generated with cucumber, I've also noticed that duration unit is in nanosecond.
This said, I haven't found any specs/schema neither.
