### ISSUE TITLE
Tags specified after a scenario outline examples table causes traceback

### ISSUE THREAD

**Issue by rscrimojr** [radish-bdd/radish#105]
I am using Python 2.7.10, MacOS Sierra version 10.12.4 and Radish-BDD version 0.4.1

With the feature file of:

```gherkin
Feature: A test feature for issues with tags specified after a scenario outline examples table
  A feature description here

  @do_it1
  Scenario Outline: Fruit Consumption 1
    Given I have a <fruit>
    When I <method> the <fruit>
    Then I get lots of <what>

    Examples:
      | fruit  | method | what      |
      | apple  | eat    | fiber     |
      | banana | blend  | nutrients |

  @do_it2
  Scenario: Fruit Consumption 2
    Given I have a appple
    When I eat the apple
    Then I get lots of fiber
```

steps.py contents:

```python
import re

from radish import given, when, then


@given(re.compile(r'I have a (.+)$'))
def my_step(step, fruit):
    pass

@when(re.compile(r'I (.+?) the (.+)$'))
def my_step(step, method, fruit):
    pass

@then(re.compile(r'I get lots of (.+)$'))
def my_setp(step, what):
    pass
```

Then:

```
$ radish tests/stuff/features/ -b tests/stuff --early-exit
Feature: A test feature for issues with tags specified after a table  # tests/stuff/features/stuff.feature
    A feature description here

    @do_it1
    Scenario Outline: Fruit Consumption 1
        Given I have a <fruit>
        When I <method> the <fruit>
        Then I get lots of <what>

1 features (0 passed)
4 scenarios (0 passed)
12 steps (0 passed)
Run 1493994918 finished within 0:0.0 minutes
Error: Hook 'console_writer_after_each_scenario' from .../lib/python2.7/site-packages/radish/extensions/console_writer.py:246 raised: 'RadishError: Invalid colum_index to get column width for ScenarioOutline 'Fruit Consumption 1''

Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/radish/hookregistry.py", line 85, in call
    hook(*args, **kwargs)
  File ".../lib/python2.7/site-packages/radish/extensions/console_writer.py", line 257, in console_writer_after_each_scenario
    u" | ".join("{1: <{0}}".format(scenario.get_column_width(i), x) for i, x in enumerate(scenario.examples_header))
  File ".../lib/python2.7/site-packages/radish/extensions/console_writer.py", line 257, in <genexpr>
    u" | ".join("{1: <{0}}".format(scenario.get_column_width(i), x) for i, x in enumerate(scenario.examples_header))
  File ".../lib/python2.7/site-packages/radish/scenariooutline.py", line 80, in get_column_width
    raise RadishError("Invalid colum_index to get column width for ScenarioOutline '{0}'".format(self.sentence))
RadishError: Invalid colum_index to get column width for ScenarioOutline 'Fruit Consumption 1'
```

**Comment by timofurrer** [comment]
Thanks for the report! I'll have a look at it!

**Comment by rscrimojr** [comment]
Thanks Timo.

**Comment by rscrimojr** [comment]
Thanks for the reformat.  I will keep that in mind for future reports. 👍
