### ISSUE TITLE
Traceback occurs when step sentence is used with cardinality and standard types

### ISSUE THREAD

**Issue by rscrimojr** [radish-bdd/radish#130]
I am using Python 2.7.10, MacOS Sierra version 10.12.4 and Radish-BDD version 0.6.2

```
>>> radish.__VERSION__
'0.6.2'
>>>
```

With the feature file of:

```
Feature: A test feature for issues with cardinality used in sentence parameters
  A feature description here

  Scenario: Fruit Consumption 1
    Given I have a apple
    When I eat the apple,pear,banana
    Then I get lots of fiber
```
steps.py contents:

```
import re

from radish import given, when, then


@given(r'I have a {fruit:S}')
def my_step(step, fruit):
    pass

@when(r'I {method:S} the {fruits:S+}')
def my_step(step, method, fruits):
    pass

@then(r'I get lots of {what:S}')
def my_step(step, what):
    pass
```

Then:

```
$ radish -b tests/stuff/ tests/stuff/features/ --early-exit
Error: 'S'

Traceback (most recent call last):
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/errororacle.py", line 59, in _decorator
    return func(*args, **kwargs)
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/main.py", line 199, in main
    return method(core)
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/main.py", line 66, in run_features
    merge_steps(core.features, StepRegistry().steps)
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/matcher.py", line 63, in merge_steps
    merge_step(step, steps)
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/matcher.py", line 73, in merge_step
    match = match_step(step.context_sensitive_sentence, steps)
  File ".../python-2.7.10/lib/python2.7/site-packages/radish/matcher.py", line 101, in match_step
    parser = Parser(pattern, CustomTypeRegistry().custom_types)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 44, in __init__
    missing = self.create_missing_types(schema, extra_types, type_builder)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 70, in create_missing_types
    return type_builder.create_type_variants(missing, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 163, in create_type_variants
    type_variant = cls.create_type_variant(type_name, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 135, in create_type_variant
    raise MissingTypeError(primary_name)
MissingTypeError: 'S'
```

NOTE:  The test runs without issues if the cardinality, e.g. '+', is not specified in the step sentence decorator.  Also, tried the cardinality with 'd' as well with similar message.

So,

Given the same feature file as above and the following changes to the steps.py:

```
...
@when(r'I {method:S} the {fruits:S}')
def my_step(step, method, fruits):
    pass
...
```

Then:

```
$ radish -b tests/stuff/ tests/stuff/features/ --early-exit
Feature: A test feature for issues with cardinality used in sentence parameters  # tests/stuff/features/stuff.feature
    A feature description here

    Scenario: Fruit Consumption 1
        Given I have a apple
        When I eat the apple,pear,banana
        Then I get lots of fiber

1 features (1 passed)
1 scenarios (1 passed)
3 steps (3 passed)
Run 1496682564 finished within 0:3.009481 minutes
```

**Comment by timofurrer** [comment]
Thanks for the report :beers:

I didn't have the time to dig into it too much but it looks like an issue with `parse_type` - the package radish uses for those `parse` cardinality extensions.

If you have some time you could try and use `parse_type` directly to parse this string and see if it works.

I'll dig into it as soon as I've some time to do so.

**Comment by rscrimojr** [comment]
@timofurrer I will see if I can make some time today to investigate.

**Comment by rscrimojr** [comment]
@timofurrer Okay looks like parse_type is not working with standard types with cardinality. 

E.g.
```
>>> from parse_type.cfparse import Parser
>>> p = Parser(r'I {method:S} the {fruits:S+}', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 44, in __init__
    missing = self.create_missing_types(schema, extra_types, type_builder)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 70, in create_missing_types
    return type_builder.create_type_variants(missing, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 163, in create_type_variants
    type_variant = cls.create_type_variant(type_name, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 135, in create_type_variant
    raise MissingTypeError(primary_name)
parse_type.cardinality_field.MissingTypeError: 'S'
```

Then if I do not use named fields, I get this:

```
>>> from parse_type.cfparse import Parser
>>> p = Parser(r'I {:S} the {:S+}', {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 44, in __init__
    missing = self.create_missing_types(schema, extra_types, type_builder)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cfparse.py", line 70, in create_missing_types
    return type_builder.create_type_variants(missing, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 163, in create_type_variants
    type_variant = cls.create_type_variant(type_name, type_dict)
  File ".../python-2.7.10/lib/python2.7/site-packages/parse_type/cardinality_field.py", line 135, in create_type_variant
    raise MissingTypeError(primary_name)
parse_type.cardinality_field.MissingTypeError: 'S'
```
I don't think this is supposed to happen.

However, when I do the following, we get the expected result:

```
>>> p = Parser(r'I {:S} the {:S}.', {})
>>> m = p.search(r'I 9 the 10.', evaluate_result=False)
>>> m
<parse.Match object at 0x106d95d90>
>>> m.evaluate_result()
<Result ('9', '10') {}>
>>> m = p.search(r'I eat the apple,pear,banana.', evaluate_result=False)
>>> m
<parse.Match object at 0x106d95b90>
>>> m.evaluate_result()
<Result ('eat', 'apple,pear,banana') {}>
>>>
```

**Comment by timofurrer** [comment]
Thank you very much for the investigation! :beers: 

Can you create an issue with your findings here: https://github.com/jenisys/parse_type

If you don't want to I can do it as well.

**Comment by rscrimojr** [comment]
Opened issue: https://github.com/jenisys/parse_type/issues/9

**Comment by timofurrer** [comment]
I'm closing this - see the previously marked issue in parse_type.
