### ISSUE TITLE
Unittests for radish functions

### ISSUE THREAD

**Issue by Draqun** [radish-bdd/radish#163]
I want write some unittests for my functions and cannot mock world object.

My custom_terrains.py
```
from radish import after
from radish import before
from radish import world

from user_tests_modules.templates import base as b


@before.each_scenario
def create_test_obj(scenario):
    """Function creating BaseTest object and put them to the scenario context"""
    scenario.context.test_object = b.BaseTest(world.config.user_data["dev_parameters"],
                                              world.config.user_data["test_devices"],
                                              world.config.user_data["test_parameters"],
                                              world.config.user_data["path_to_test_file"],
                                              world.config.user_data["test_dir_path_it"])


@after.each_scenario
def delete_test_obj(scenario):
    """Remove BaseTest from the scenario context"""
    del scenario.context.test_object
```

And my tests
```
#!/usr/bin/env python3

import mock
import unittest

try:
    from user_tests_modules.radish_modules import custom_terrain as t
except ImportError:
    from templates import base as b

class TestTerrain(unittest.TestCase):
    @mock.patch("radish.world")
    def test_create_test_obj(self, mock_radish_world):
        mock_step = mock.MagicMock()
        mock_step.config = mock.MagicMock()
        mock_step.config.user_data = mock.MagicMock()
        t.create_test_obj(mock_step)

        self.assertIsNotNone(mock_step.context.test_object)


if "__main__" == __name__:
    unittest.main()
```

And error
```
ERROR: test_create_test_obj (user_tests_modules.radish_tests.custom_terrain.TestTerrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/damian/PycharmProjects/bluebox/test_framework/test_framework_venv/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/damian/PycharmProjects/bluebox/test_framework/user_tests_modules/radish_tests/custom_terrain.py", line 17, in test_create_test_obj
    t.create_test_obj(mock_step)
  File "/home/damian/PycharmProjects/bluebox/test_framework/user_tests_modules/radish_modules/custom_terrain.py", line 20, in create_test_obj
    scenario.context.test_object = b.BaseTest(world.config.user_data["dev_parameters"],
AttributeError: '_thread._local' object has no attribute 'config'
```

Any tip how to patch world object?

Thank you.
Best regards.

**Comment by timofurrer** [comment]
This does not seem to be an issue with radish directly, but rather with your mocking.

I guess the path to the patched object is wrong.
If I have some time I'll figure out the correct patch path.
