### ISSUE TITLE
Can not use PIPE (|) character in Scenario Outlines

### ISSUE THREAD

**Issue by eerkunt** [radish-bdd/radish#351]
Hello,

As also tried in https://github.com/eerkunt/terraform-compliance/issues/110, we can't use ( or escape ) `PIPE` `|` character within Scenario Outlines.

Example Feature ;
```cucumber
  Scenario Outline: Ensure that my specific tags are defined
    Given I have resource that supports tags defined
    When it contains tags
    Then it must contain <tag_keys>
    And its value must match the "<pattern>" regex

    Examples:
      | tag_keys        | pattern           |
      | BusinessUnit    | ^(IT\|Marketing)$ |
```

Stack Trace :
```
Error: Hook 'console_writer_after_each_scenario' from /Users/sharky/Repository/venv3/lib/python3.7/site-packages/radish/extensions/formatters/gherkin.py:425 raised: 'RadishError: Invalid colum_index to get column width for ScenarioOutline 'Ensure that my specific tags are defined''

Traceback (most recent call last):
  File "/Users/sharky/Repository/venv3/lib/python3.7/site-packages/radish/scenariooutline.py", line 126, in get_column_width
    len(self.examples_header[column_index]),
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../venv3/lib/python3.7/site-packages/radish/hookregistry.py", line 132, in call
    func(model, *args, **kwargs)
  File "/.../venv3/lib/python3.7/site-packages/radish/extensions/formatters/gherkin.py", line 467, in console_writer_after_each_scenario
    for i, x in enumerate(scenario.example.data)
  File "/...venv3/lib/python3.7/site-packages/radish/extensions/formatters/gherkin.py", line 467, in <genexpr>
    for i, x in enumerate(scenario.example.data)
  File "/.../venv3/lib/python3.7/site-packages/radish/scenariooutline.py", line 131, in get_column_width
    self.sentence
radish.exceptions.RadishError: Invalid colum_index to get column width for ScenarioOutline 'Ensure that my specific tags are defined'
```

It looks like some frameworks already support this, any chance we can see this support in `radish-bdd` ?

Thanks!

**Comment by timofurrer** [comment]
Seems like a bug to me. I'll have a closer look into it this evening. Thanks for reporting it :tada:

**Comment by timofurrer** [comment]
I've implemented a fix with f1acaec and I'll release that asap.

**Comment by eerkunt** [comment]
Thanks for the quick fix mate. I will update this issue after testing with the new version.

**Comment by timofurrer** [comment]
You are very welcome!

Can you give https://github.com/radish-bdd/radish/releases/tag/v0.13.1 a shot please :)

**Comment by eerkunt** [comment]
Tested with `0.13.1`, confirming it is working as intended :)

Thanks for the quick fix!

**Comment by timofurrer** [comment]
Awesome :tada: Always a pleasure!
