### ISSUE TITLE
Is radish supported on windows?

### ISSUE THREAD

**Issue by SamuelYvon** [radish-bdd/radish#49]
Hi!

I tried to run radish on windows and I get this stacktrace:

```
Error: No module named 'syslog'

Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\errororacle.py", line 58, in _decorator
    return func(*args, **kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\main.py", line 132, in main
    load_modules(os.path.join(os.path.dirname(__file__), "extensions"))
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\loader.py", line 24, in load_modules
    load_module(os.path.join(p, filename))
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\loader.py", line 40, in load_module
    raise e
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\loader.py", line 37, in load_module
    __import__(module_name)
  File "c:\program files (x86)\python35-32\lib\site-packages\radish\extensions\syslog_writer.py", line 13, in <module>
    import syslog
ImportError: No module named 'syslog'
```

I am running python 3.5 (it also is the only version installed on my machine).
Is the project supported on windows?

**Comment by timofurrer** [comment]
radish is not officially supported on windows yet. However, I've just pushed a change which only import syslog if it's actually required via the `--syslog` option.

What probably won't work either are the color sequences. 

Because I don't have a windows machine I can't verify what works and what not. I'm happy to take contributions though or look for solution for a particular problem.

**Comment by SamuelYvon** [comment]
I would be happy to contribute! I will update and continue updating you!

**Comment by timofurrer** [comment]
That's awesome! Thanks. If you want stop by on [gitter](https://gitter.im/radish-bdd/radish).

**Comment by timofurrer** [comment]
I close this one in favor of #50 :tada:
