### ISSUE TITLE
Errors in working with colorful

### ISSUE THREAD

**Issue by valenok007** [radish-bdd/radish#78]
Python 3.5, radish - latest from pip (0.3.1?)

after upgrade, i catch error:

> 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/colorful/core.py", line 99, in translate_colorname_to_ansi_code
    red, green, blue = colorpalette[colorname]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/radish", line 7, in <module>
    from radish.main import main
  File "/usr/local/lib/python3.5/dist-packages/radish/main.py", line 8, in <module>
    from colorful import colorful
  File "<frozen importlib._bootstrap>", line 1006, in _handle_fromlist
  File "/usr/local/lib/python3.5/dist-packages/colorful/__init__.py", line 116, in __getattr__
    return getattr(self.colorful, name)
  File "/usr/local/lib/python3.5/dist-packages/colorful/core.py", line 325, in __getattr__
    style = translate_style(name, self.colormode, self.colorpalette)
  File "/usr/local/lib/python3.5/dist-packages/colorful/core.py", line 168, in translate_style
    part, FOREGROUND_COLOR_OFFSET, colormode, colorpalette))
  File "/usr/local/lib/python3.5/dist-packages/colorful/core.py", line 102, in translate_colorname_to_ansi_code
    colorname))
colorful.core.ColorfulError: the color "" is unknown. Use a color in your color palette (by default: X11 rgb.txt)

previous version works good. Problem appeared on mac, linux permanent

**Comment by valenok007** [comment]
Solved. Just need update colorful to 0.3.1

**Comment by timofurrer** [comment]
Thanks for reporting the issue!

I've just pinned the colorful version to `0.3.1` until the new version of [colorful](https://github.com/timofurrer/colorful) is released.

:beers:
