### ISSUE TITLE
--early-exit produces traceback when an AssertionError/Exception is fired on a step

### ISSUE THREAD

**Issue by rscrimojr** [radish-bdd/radish#92]
I am using Python 2.7.10, MacOS Sierra version 10.12.4 and Radish-BDD version 0.4.0
I am using --early-exit on the command line when an AssertionError/Exception is fired on a step
then this trackback occurs:

Error: unsupported operand type(s) for |=: 'int' and 'NoneType'

Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/radish/errororacle.py", line 58, in _decorator
    return func(*args, **kwargs)
  File ".../lib/python2.7/site-packages/radish/main.py", line 181, in main
    return method(core)
  File ".../lib/python2.7/site-packages/radish/main.py", line 75, in run_features
    return runner.start(core.features_to_run, marker=world.config.marker)
  File ".../lib/python2.7/site-packages/radish/runner.py", line 31, in _decorator
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File ".../lib/python2.7/site-packages/radish/runner.py", line 48, in _wrapper
    return func(self, model_instance, *args, **kwargs)
  File ".../lib/python2.7/site-packages/radish/runner.py", line 77, in start
    returncode |= self.run_feature(feature)
  File ".../lib/python2.7/site-packages/radish/runner.py", line 31, in _decorator
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File ".../lib/python2.7/site-packages/radish/runner.py", line 48, in _wrapper
    return func(self, model_instance, *args, **kwargs)
  File ".../lib/python2.7/site-packages/radish/runner.py", line 96, in run_feature
    returncode |= self.run_scenario(scenario)
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'

**Comment by timofurrer** [comment]
Fixed with #93 :tada: Thanks!

**Comment by rscrimojr** [comment]
@timofurrer Thanks Tim.  Very excellent job on this great Python BDD Framework. I ❤️ Radish BDD!
